#!/bin/bash

# Stop script execution on error
set -e

# Base path where files will be generated
HELPERS_DIR=$1
WORKSPACE_NAME=$2
TEAM_NAME=$3
APP_NAME=$4

if [ -z "$HELPERS_DIR" ]; then
    echo "❌ You must provide a directory path for file creation."
    exit 1
fi

if [ -z "$WORKSPACE_NAME" ]; then
    echo "❌ You must provide a workspace name for file creation."
    exit 1
fi

if [ -z "$TEAM_NAME" ]; then
    echo "❌ You must provide a team name for file creation."
    exit 1
fi

GIT_USER_NAME=$(git config user.name)

# Generate the Workspace
echo "📄 Creating Workspace.swift file..."
cat <<EOF > "$HELPERS_DIR/Workspace.swift"
import ProjectDescription

let workspace = Workspace(
    name: "${WORKSPACE_NAME}",
    projects: [
        "Shared/**",
        "${APP_NAME}/**"
    ],
    fileHeaderTemplate: """
//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ${TEAM_NAME} All rights reserved.
//
""",
    additionalFiles: [],
    generationOptions: .options(
        enableAutomaticXcodeSchemes: false,
        autogeneratedWorkspaceSchemes: .disabled
    )
)
EOF

echo "✅ Workspace.swift file created successfully"
echo "$HELPERS_DIR/Workspace.swift"
echo ""